name: Temp pipeline

on:
  push:

jobs:
  temp-job:
    runs-on: ${{ vars.RUNNER_TAG }}
    steps:
      - name: checking out to repo
        uses: actions/checkout@v4
      - name: SSH setup
        uses: ./.github/actions
        with:
          private_key: ${{ secrets.SSH_KEY }}